## Database visualization, using postgres

In [1]:
from sqlalchemy import create_engine, MetaData
from sqlalchemy_utils import database_exists, create_database
from urllib import parse

import pandas as pd

In [2]:
# Name of your database - this database does NOT exist yet (create it below with `create_database()`)
database = 'my-new-database'

# Connection details according to docker-compose.yml - do not change this
dialect = 'postgresql'  # Could be almost any other DB technology
host = 'postgres'
port = 5432
username = 'postgres'
password = 'password'
# URL-encode password for characters like %, ä, ...
password = parse.quote_plus(password)

url = f'{dialect}://{username}:{password}@{host}:{port}/{database}'
engine = create_engine(url)

In [3]:
if not database_exists(engine.url):
    create_database(engine.url)

print(f'Database "{database}" exists: {database_exists(engine.url)}')

Database "my-new-database" exists: True

In [4]:
sql = open("/home/jovyan/work/northwind.sql").read()
with engine.begin() as connection:
    connection.execute(sql)

In [5]:
# Postgres - let's use the standard/default schema
schema = 'public'

In [6]:
# Associate the metadata with our database (the engine-object)
meta = MetaData(bind=engine, schema=schema)
# Load the existing database metadata from the database into meta
meta.reflect()
# Print all tables
meta.tables.keys()

/opt/conda/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:3132: SAWarning: Did not recognize type 'bpchar' of column 'customer_id'
  util.warn(
/opt/conda/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:3132: SAWarning: Did not recognize type 'bpchar' of column 'region_description'
  util.warn(
/opt/conda/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:3132: SAWarning: Did not recognize type 'bpchar' of column 'territory_description'
  util.warn(
/opt/conda/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:3132: SAWarning: Did not recognize type 'bpchar' of column 'customer_type_id'
  util.warn(

dict_keys(['public.us_states', 'public.customers', 'public.orders', 'public.employees', 'public.shippers', 'public.products', 'public.categories', 'public.suppliers', 'public.order_details', 'public.region', 'public.territories', 'public.employee_territories', 'public.customer_demographics', 'public.customer_customer_demo'])

In [7]:
for table in meta.sorted_tables:
    for column in table.columns:
        print(f'{table.name}: {column.name}')

categories: category_id
categories: category_name
categories: description
categories: picture
customer_demographics: customer_type_id
customer_demographics: customer_desc
customers: customer_id
customers: company_name
customers: contact_name
customers: contact_title
customers: address
customers: city
customers: region
customers: postal_code
customers: country
customers: phone
customers: fax
employees: employee_id
employees: last_name
employees: first_name
employees: title
employees: title_of_courtesy
employees: birth_date
employees: hire_date
employees: address
employees: city
employees: region
employees: postal_code
employees: country
employees: home_phone
employees: extension
employees: photo
employees: notes
employees: reports_to
employees: photo_path
region: region_id
region: region_description
shippers: shipper_id
shippers: company_name
shippers: phone
suppliers: supplier_id
suppliers: company_name
suppliers: contact_name
suppliers: contact_title
suppliers: address
suppliers: city
suppliers: region
suppliers: postal_code
suppliers: country
suppliers: phone
suppliers: fax
suppliers: homepage
us_states: state_id
us_states: state_name
us_states: state_abbr
us_states: state_region
customer_customer_demo: customer_id
customer_customer_demo: customer_type_id
orders: order_id
orders: customer_id
orders: employee_id
orders: order_date
orders: required_date
orders: shipped_date
orders: ship_via
orders: freight
orders: ship_name
orders: ship_address
orders: ship_city
orders: ship_region
orders: ship_postal_code
orders: ship_country
products: product_id
products: product_name
products: supplier_id
products: category_id
products: quantity_per_unit
products: unit_price
products: units_in_stock
products: units_on_order
products: reorder_level
products: discontinued
territories: territory_id
territories: territory_description
territories: region_id
employee_territories: employee_id
employee_territories: territory_id
order_details: order_id
order_details: product_id
order_details: unit_price
order_details: quantity
order_details: discount

In [8]:
table_name = 'customers'
df = pd.read_sql_table(
    table_name,
    con=engine,
    schema=schema,
    index_col='customer_id'  # column name to use as dataframe-index (optional)
)
df

,company_name,contact_name,contact_title,address,city,region,postal_code,country,phone,fax
customer_id,,,,,,,,,,
ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,None,05021,Mexico,(5) 555-4729,(5) 555-3745
ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,None,05023,Mexico,(5) 555-3932,None
AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,None,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
...,...,...,...,...,...,...,...,...,...,...
WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,None,90110,Finland,981-443655,981-443655
WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,SP,08737-363,Brazil,(14) 555-8122,None
WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,None,21240,Finland,90-224 8858,90-224 8858
WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,None,01-012,Poland,(26) 642-7012,(26) 642-7012

In [9]:
table_name = 'customers_copy'

df.to_sql(
    table_name,
    con=engine,
    schema=schema,
    if_exists='fail',  # What to do with an existing table? Could also be `replace` or `append`
    index=True,  # Whether to write the dataframe index as an additional column. Won't be a primary key automatically!
)

In [10]:
from sqlalchemy_schemadisplay import create_schema_graph

In [11]:
# Postgres only
# SQLAlchemy has issues with the following columns when using Postgres. They all seem to be strings
offending = ['territory_description', 'region_description', 'customer_id', 'customer_type_id']

from sqlalchemy.types import VARCHAR

for table in meta.sorted_tables:
    for column in table.columns:
        if column.name in offending:
            print(f'{table.name}: {column.name}')
            column.type = VARCHAR(32)

customer_demographics: customer_type_id
customers: customer_id
region: region_description
customer_customer_demo: customer_id
customer_customer_demo: customer_type_id
orders: customer_id
territories: territory_description

In [12]:
graph = create_schema_graph(metadata=meta,
   show_datatypes=True,
   show_indexes=True,
   rankdir='LR', # From left to right (instead of top to bottom)
   concentrate=False # Don't try to join the relation lines together
)

graph.write_png('db_entity_diagram.png')